export const ROUTE_TO_MODULE_KEY: { [key: string]: string } = {
  '/': 'dashboard',
  '/cases': 'cases',
  '/case-reports': 'cases',
  '/invoices': 'invoices',
  '/payments': 'payments',
  '/expenses': 'expenses',
  '/finance': 'revenue',
  '/transactions': 'transactions',
  '/banking': 'banking',
  '/vat-audit': 'vat-audit',
  '/reports': 'reports',
  '/customers': 'customers',
  '/quotes': 'quotes',
  '/companies': 'companies',
  '/suppliers': 'suppliers',
  '/purchase': 'purchase',
  '/purchase-orders': 'suppliers',
  '/inventory': 'inventory',
  '/tools': 'inventory',
  '/stock': 'stock',
  '/assets': 'assets',
  '/clone-drives': 'clone-drives',
  '/procedures': 'kb-center',
  '/hr': 'hr-dashboard',
  '/hr/employees': 'employees',
  '/hr/recruitment': 'recruitment',
  '/hr/onboarding': 'onboarding',
  '/hr/performance': 'performance',
  '/payroll': 'payroll-dashboard',
  '/payroll/process': 'process-payroll',
  '/payroll/components': 'salary-components',
  '/payroll/history': 'payroll-history',
  '/payroll/adjustments': 'payroll-dashboard',
  '/payroll/loans': 'payroll-dashboard',
  '/payroll/settings': 'payroll-dashboard',
  '/attendance': 'attendance',
  '/leave': 'leave',
  '/timesheets': 'timesheets',
  '/settings': 'settings',
  '/users': 'user-management',
  '/integrations': 'integrations',
  '/admin': 'admin-panel',
  '/templates': 'templates',
};

export function getModuleKeyForRoute(route: string): string | null {
  return ROUTE_TO_MODULE_KEY[route] || null;
}
