-- GENERATED by scripts/country-engine/build-geo-seed.ts — DO NOT EDIT BY HAND.
-- Reference dataset version: gcc-priority-2026-06-15
-- Idempotent: ON CONFLICT (code) DO UPDATE ... WHERE source_locked IS NOT TRUE.
-- country_config is jsonb-MERGED (||), not replaced, so curated overrides survive.

INSERT INTO public.geo_countries
  (code, name, currency_code, currency_symbol, currency_position, decimal_places,
   decimal_separator, thousands_separator, locale_code, language_code, date_format,
   time_format, timezone, week_starts_on, digit_grouping, phone_format, address_format,
   country_config, config_status, data_source, source_version, reference_dataset_version)
VALUES
  ('SA', 'Saudi Arabia', 'SAR', 'ر.س', 'after', 2, '.', ',', 'ar-SA', 'ar', 'DD/MM/YYYY', '12h', 'Asia/Riyadh', 0, '3', 'XX XXX XXXX', '{"lines":["%N","%O","%A","%C %Z"]}'::jsonb, '{"currency":{"code":"SAR","symbol":"ر.س","decimal_places":2},"datetime":{"date_format":"DD/MM/YYYY","timezone":"Asia/Riyadh","weekend_days":[5,6],"week_starts_on":0},"number_format":{"digit_grouping":"3","decimal_separator":".","group_separator":","},"locale":{"code":"ar-SA"}}'::jsonb, 'formatting_ready', 'cldr+iso4217+libphonenumber', 'gcc-priority-2026-06-15', 'gcc-priority-2026-06-15'),
  ('AE', 'United Arab Emirates', 'AED', 'د.إ', 'after', 2, '.', ',', 'ar-AE', 'ar', 'DD/MM/YYYY', '12h', 'Asia/Dubai', 0, '3', 'XX XXX XXXX', '{"lines":["%N","%O","%A","%C"]}'::jsonb, '{"currency":{"code":"AED","symbol":"د.إ","decimal_places":2},"datetime":{"date_format":"DD/MM/YYYY","timezone":"Asia/Dubai","weekend_days":[5,6],"week_starts_on":0},"number_format":{"digit_grouping":"3","decimal_separator":".","group_separator":","},"locale":{"code":"ar-AE"}}'::jsonb, 'formatting_ready', 'cldr+iso4217+libphonenumber', 'gcc-priority-2026-06-15', 'gcc-priority-2026-06-15'),
  ('OM', 'Oman', 'OMR', 'ر.ع.', 'after', 3, '.', ',', 'ar-OM', 'ar', 'DD/MM/YYYY', '12h', 'Asia/Muscat', 0, '3', 'XXXX XXXX', '{"lines":["%N","%O","%A","%C %Z"]}'::jsonb, '{"currency":{"code":"OMR","symbol":"ر.ع.","decimal_places":3},"datetime":{"date_format":"DD/MM/YYYY","timezone":"Asia/Muscat","weekend_days":[5,6],"week_starts_on":0},"number_format":{"digit_grouping":"3","decimal_separator":".","group_separator":","},"locale":{"code":"ar-OM"}}'::jsonb, 'formatting_ready', 'cldr+iso4217+libphonenumber', 'gcc-priority-2026-06-15', 'gcc-priority-2026-06-15'),
  ('KW', 'Kuwait', 'KWD', 'د.ك', 'after', 3, '.', ',', 'ar-KW', 'ar', 'DD/MM/YYYY', '12h', 'Asia/Kuwait', 0, '3', 'XXXX XXXX', '{"lines":["%N","%O","%A","%C %Z"]}'::jsonb, '{"currency":{"code":"KWD","symbol":"د.ك","decimal_places":3},"datetime":{"date_format":"DD/MM/YYYY","timezone":"Asia/Kuwait","weekend_days":[5,6],"week_starts_on":0},"number_format":{"digit_grouping":"3","decimal_separator":".","group_separator":","},"locale":{"code":"ar-KW"}}'::jsonb, 'formatting_ready', 'cldr+iso4217+libphonenumber', 'gcc-priority-2026-06-15', 'gcc-priority-2026-06-15'),
  ('QA', 'Qatar', 'QAR', 'ر.ق', 'after', 2, '.', ',', 'ar-QA', 'ar', 'DD/MM/YYYY', '12h', 'Asia/Qatar', 0, '3', 'XXXX XXXX', '{"lines":["%N","%O","%A","%C"]}'::jsonb, '{"currency":{"code":"QAR","symbol":"ر.ق","decimal_places":2},"datetime":{"date_format":"DD/MM/YYYY","timezone":"Asia/Qatar","weekend_days":[5,6],"week_starts_on":0},"number_format":{"digit_grouping":"3","decimal_separator":".","group_separator":","},"locale":{"code":"ar-QA"}}'::jsonb, 'formatting_ready', 'cldr+iso4217+libphonenumber', 'gcc-priority-2026-06-15', 'gcc-priority-2026-06-15'),
  ('BH', 'Bahrain', 'BHD', 'د.ب', 'after', 3, '.', ',', 'ar-BH', 'ar', 'DD/MM/YYYY', '12h', 'Asia/Bahrain', 0, '3', 'XXXX XXXX', '{"lines":["%N","%O","%A","%C %Z"]}'::jsonb, '{"currency":{"code":"BHD","symbol":"د.ب","decimal_places":3},"datetime":{"date_format":"DD/MM/YYYY","timezone":"Asia/Bahrain","weekend_days":[5,6],"week_starts_on":0},"number_format":{"digit_grouping":"3","decimal_separator":".","group_separator":","},"locale":{"code":"ar-BH"}}'::jsonb, 'formatting_ready', 'cldr+iso4217+libphonenumber', 'gcc-priority-2026-06-15', 'gcc-priority-2026-06-15'),
  ('GB', 'United Kingdom', 'GBP', '£', 'before', 2, '.', ',', 'en-GB', 'en', 'DD/MM/YYYY', '24h', 'Europe/London', 1, '3', 'XXXX XXXXXX', '{"lines":["%N","%O","%A","%C","%Z"]}'::jsonb, '{"currency":{"code":"GBP","symbol":"£","decimal_places":2},"datetime":{"date_format":"DD/MM/YYYY","timezone":"Europe/London","weekend_days":[6,0],"week_starts_on":1},"number_format":{"digit_grouping":"3","decimal_separator":".","group_separator":","},"locale":{"code":"en-GB"}}'::jsonb, 'formatting_ready', 'cldr+iso4217+libphonenumber', 'gcc-priority-2026-06-15', 'gcc-priority-2026-06-15'),
  ('IN', 'India', 'INR', '₹', 'before', 2, '.', ',', 'en-IN', 'en', 'DD/MM/YYYY', '12h', 'Asia/Kolkata', 1, '3;2', 'XXXXX XXXXX', '{"lines":["%N","%O","%A","%C","%S %Z"]}'::jsonb, '{"currency":{"code":"INR","symbol":"₹","decimal_places":2},"datetime":{"date_format":"DD/MM/YYYY","timezone":"Asia/Kolkata","weekend_days":[0,6],"week_starts_on":1},"number_format":{"digit_grouping":"3;2","decimal_separator":".","group_separator":","},"locale":{"code":"en-IN"}}'::jsonb, 'formatting_ready', 'cldr+iso4217+libphonenumber', 'gcc-priority-2026-06-15', 'gcc-priority-2026-06-15'),
  ('US', 'United States', 'USD', '$', 'before', 2, '.', ',', 'en-US', 'en', 'MM/DD/YYYY', '12h', 'America/New_York', 0, '3', '(XXX) XXX-XXXX', '{"lines":["%N","%O","%A","%C, %S %Z"]}'::jsonb, '{"currency":{"code":"USD","symbol":"$","decimal_places":2},"datetime":{"date_format":"MM/DD/YYYY","timezone":"America/New_York","weekend_days":[6,0],"week_starts_on":0},"number_format":{"digit_grouping":"3","decimal_separator":".","group_separator":","},"locale":{"code":"en-US"}}'::jsonb, 'formatting_ready', 'cldr+iso4217+libphonenumber', 'gcc-priority-2026-06-15', 'gcc-priority-2026-06-15')
ON CONFLICT (code) DO UPDATE SET
  currency_code = EXCLUDED.currency_code,
  currency_symbol = EXCLUDED.currency_symbol,
  currency_position = EXCLUDED.currency_position,
  decimal_places = EXCLUDED.decimal_places,
  decimal_separator = EXCLUDED.decimal_separator,
  thousands_separator = EXCLUDED.thousands_separator,
  locale_code = EXCLUDED.locale_code,
  language_code = EXCLUDED.language_code,
  date_format = EXCLUDED.date_format,
  time_format = EXCLUDED.time_format,
  timezone = EXCLUDED.timezone,
  week_starts_on = EXCLUDED.week_starts_on,
  digit_grouping = EXCLUDED.digit_grouping,
  phone_format = EXCLUDED.phone_format,
  address_format = EXCLUDED.address_format,
  country_config = geo_countries.country_config || EXCLUDED.country_config,
  config_status = EXCLUDED.config_status,
  data_source = EXCLUDED.data_source,
  source_version = EXCLUDED.source_version,
  reference_dataset_version = EXCLUDED.reference_dataset_version,
  updated_at = now()
WHERE geo_countries.source_locked IS NOT TRUE;
