-- P0 performance migration: RLS helper calls -> InitPlan scalar sub-selects
-- Audit: docs/superpowers/specs/2026-07-09-e2e-performance-audit.md (PERF-01/PERF-02/RLS-PER-ROW-HELPERS)
-- Mechanism: bare SECURITY DEFINER helper calls in policy predicates are re-evaluated
-- PER ROW (never InitPlanned). Wrapping each call in a scalar sub-select (SELECT fn())
-- evaluates it once per statement. Measured on live cases (2,016 rows):
-- count(*) 642ms -> ~7ms. Semantics unchanged: OR is commutative and every wrapped
-- helper is a zero-arg/constant-arg stable JWT/profile reader.
-- Generated mechanically from pg_policies; reverse-transform-verified against the
-- pre-migration expressions. Business-unit policies additionally reorder their OR
-- chain cheapest-first (free column checks before helper InitPlans).

-- is_portal_user reads only JWT claims; plpgsql defaulted it to VOLATILE which
-- blocks InitPlan/caching anywhere it is used.
-- Rollout guard (reviewer recommendation): 665 ALTER POLICYs hold AccessExclusiveLocks
-- until commit; abort cleanly instead of queueing behind a surprise long reader.
SET LOCAL lock_timeout = '10s';

ALTER FUNCTION public.is_portal_user() STABLE;

ALTER POLICY "account_balance_snapshots_delete" ON public."account_balance_snapshots" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "account_balance_snapshots_tenant_isolation" ON public."account_balance_snapshots" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "account_transfers_delete" ON public."account_transfers" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "account_transfers_tenant_isolation" ON public."account_transfers" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "accounting_locales_delete" ON public."accounting_locales" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "accounting_locales_tenant_isolation" ON public."accounting_locales" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "advance_vouchers_delete" ON public."advance_vouchers" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "advance_vouchers_tenant_isolation" ON public."advance_vouchers" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "asset_assignments_delete" ON public."asset_assignments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "asset_assignments_tenant_isolation" ON public."asset_assignments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "asset_categories_delete" ON public."asset_categories" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "asset_categories_tenant_isolation" ON public."asset_categories" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "asset_depreciation_delete" ON public."asset_depreciation" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "asset_depreciation_tenant_isolation" ON public."asset_depreciation" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "asset_maintenance_delete" ON public."asset_maintenance" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "asset_maintenance_tenant_isolation" ON public."asset_maintenance" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "assets_delete" ON public."assets" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "assets_tenant_isolation" ON public."assets" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "attendance_records_delete" ON public."attendance_records" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "attendance_records_tenant_isolation" ON public."attendance_records" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "audit_trails_tenant_isolation" ON public."audit_trails" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "bank_accounts_delete" ON public."bank_accounts" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "bank_accounts_tenant_isolation" ON public."bank_accounts" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "bank_reconciliation_sessions_delete" ON public."bank_reconciliation_sessions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "bank_reconciliation_sessions_tenant_isolation" ON public."bank_reconciliation_sessions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "bank_transactions_delete" ON public."bank_transactions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "bank_transactions_tenant_isolation" ON public."bank_transactions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "billing_coupons_delete" ON public."billing_coupons" USING (( SELECT is_platform_admin() ));
ALTER POLICY "billing_coupons_insert" ON public."billing_coupons" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "billing_coupons_update" ON public."billing_coupons" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "billing_events_delete" ON public."billing_events" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "billing_events_tenant_isolation" ON public."billing_events" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "billing_invoice_items_delete" ON public."billing_invoice_items" USING (( SELECT is_platform_admin() ));
ALTER POLICY "billing_invoice_items_insert" ON public."billing_invoice_items" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "billing_invoice_items_select" ON public."billing_invoice_items" USING ((EXISTS ( SELECT 1
   FROM billing_invoices bi
  WHERE ((bi.id = billing_invoice_items.invoice_id) AND ((bi.tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() ))))));
ALTER POLICY "billing_invoice_items_update" ON public."billing_invoice_items" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "billing_invoices_delete" ON public."billing_invoices" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "billing_invoices_tenant_isolation" ON public."billing_invoices" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "branches_delete" ON public."branches" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "branches_tenant_isolation" ON public."branches" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "branding_themes_delete" ON public."branding_themes" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "branding_themes_insert" ON public."branding_themes" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "branding_themes_tenant_isolation" ON public."branding_themes" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "branding_themes_update" ON public."branding_themes" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "case_attachments_delete" ON public."case_attachments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_attachments_tenant_isolation" ON public."case_attachments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_communications_delete" ON public."case_communications" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_communications_portal_read" ON public."case_communications" USING (((deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM cases c
  WHERE ((c.id = case_communications.case_id) AND (c.customer_id = ( SELECT get_current_portal_customer_id() )))))));
ALTER POLICY "case_communications_tenant_isolation" ON public."case_communications" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_device_activity_delete" ON public."case_device_activity" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_device_activity_tenant_isolation" ON public."case_device_activity" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_devices_business_unit_isolation" ON public."case_devices" USING (((business_unit_id IS NULL) OR (( SELECT get_current_business_unit_id() ) IS NULL) OR (NOT ( SELECT business_unit_scoping_enabled() )) OR (business_unit_id = ( SELECT get_current_business_unit_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_devices_delete" ON public."case_devices" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_devices_portal_read" ON public."case_devices" USING (((deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM cases c
  WHERE ((c.id = case_devices.case_id) AND (c.customer_id = ( SELECT get_current_portal_customer_id() )))))));
ALTER POLICY "case_devices_tenant_isolation" ON public."case_devices" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_diagnostics_delete" ON public."case_diagnostics" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_diagnostics_tenant_isolation" ON public."case_diagnostics" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_engineers_delete" ON public."case_engineers" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_engineers_tenant_isolation" ON public."case_engineers" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_follow_ups_delete" ON public."case_follow_ups" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_follow_ups_tenant_isolation" ON public."case_follow_ups" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_internal_notes_delete" ON public."case_internal_notes" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_internal_notes_tenant_isolation" ON public."case_internal_notes" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_internal_notes_update" ON public."case_internal_notes" USING (((created_by = ( SELECT auth.uid() AS uid)) OR ( SELECT has_role('admin'::text) ))) WITH CHECK (((created_by = ( SELECT auth.uid() AS uid)) OR ( SELECT has_role('admin'::text) )));
ALTER POLICY "case_job_history_tenant_isolation" ON public."case_job_history" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_milestones_delete" ON public."case_milestones" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_milestones_tenant_isolation" ON public."case_milestones" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_portal_visibility_delete" ON public."case_portal_visibility" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_portal_visibility_portal_read" ON public."case_portal_visibility" USING (((deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM cases c
  WHERE ((c.id = case_portal_visibility.case_id) AND (c.customer_id = ( SELECT get_current_portal_customer_id() )))))));
ALTER POLICY "case_portal_visibility_tenant_isolation" ON public."case_portal_visibility" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_qa_checklists_delete" ON public."case_qa_checklists" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_qa_checklists_insert" ON public."case_qa_checklists" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "case_qa_checklists_tenant_isolation" ON public."case_qa_checklists" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_qa_checklists_update" ON public."case_qa_checklists" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "case_quote_items_delete" ON public."case_quote_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_quote_items_portal_read" ON public."case_quote_items" USING (((deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM (case_quotes q
     JOIN cases c ON ((c.id = q.case_id)))
  WHERE ((q.id = case_quote_items.quote_id) AND (q.deleted_at IS NULL) AND (c.deleted_at IS NULL) AND (c.customer_id = ( SELECT get_current_portal_customer_id() )))))));
ALTER POLICY "case_quote_items_tenant_isolation" ON public."case_quote_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_quotes_delete" ON public."case_quotes" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_quotes_portal_read" ON public."case_quotes" USING (((deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM cases c
  WHERE ((c.id = case_quotes.case_id) AND (c.customer_id = ( SELECT get_current_portal_customer_id() )))))));
ALTER POLICY "case_quotes_tenant_isolation" ON public."case_quotes" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_recovery_attempts_delete" ON public."case_recovery_attempts" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "case_recovery_attempts_insert" ON public."case_recovery_attempts" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "case_recovery_attempts_tenant_isolation" ON public."case_recovery_attempts" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "case_recovery_attempts_update" ON public."case_recovery_attempts" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "case_status_transitions_delete" ON public."case_status_transitions" USING (( SELECT is_platform_admin() ));
ALTER POLICY "case_status_transitions_insert" ON public."case_status_transitions" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "case_status_transitions_update" ON public."case_status_transitions" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "cases_business_unit_isolation" ON public."cases" USING (((branch_id IS NULL) OR (( SELECT get_current_business_unit_id() ) IS NULL) OR (NOT ( SELECT business_unit_scoping_enabled() )) OR (branch_id = ( SELECT get_current_business_unit_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "cases_delete" ON public."cases" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "cases_portal_read" ON public."cases" USING (((deleted_at IS NULL) AND (customer_id = ( SELECT get_current_portal_customer_id() ))));
ALTER POLICY "cases_tenant_isolation" ON public."cases" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "catalog_accessories_delete" ON public."catalog_accessories" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_accessories_insert" ON public."catalog_accessories" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_accessories_update" ON public."catalog_accessories" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_brands_delete" ON public."catalog_device_brands" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_device_brands_insert" ON public."catalog_device_brands" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_brands_update" ON public."catalog_device_brands" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_capacities_delete" ON public."catalog_device_capacities" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_device_capacities_insert" ON public."catalog_device_capacities" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_capacities_update" ON public."catalog_device_capacities" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_component_statuses_delete" ON public."catalog_device_component_statuses" USING (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_device_component_statuses_insert" ON public."catalog_device_component_statuses" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_device_component_statuses_update" ON public."catalog_device_component_statuses" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_device_conditions_delete" ON public."catalog_device_conditions" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_device_conditions_insert" ON public."catalog_device_conditions" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_conditions_update" ON public."catalog_device_conditions" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_encryption_delete" ON public."catalog_device_encryption" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_device_encryption_insert" ON public."catalog_device_encryption" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_encryption_update" ON public."catalog_device_encryption" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_form_factors_delete" ON public."catalog_device_form_factors" USING (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_device_form_factors_insert" ON public."catalog_device_form_factors" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_device_form_factors_update" ON public."catalog_device_form_factors" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_device_head_counts_delete" ON public."catalog_device_head_counts" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_device_head_counts_insert" ON public."catalog_device_head_counts" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_head_counts_update" ON public."catalog_device_head_counts" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_interfaces_delete" ON public."catalog_device_interfaces" USING (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_device_interfaces_insert" ON public."catalog_device_interfaces" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_device_interfaces_update" ON public."catalog_device_interfaces" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_device_made_in_delete" ON public."catalog_device_made_in" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_device_made_in_insert" ON public."catalog_device_made_in" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_made_in_update" ON public."catalog_device_made_in" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_platter_counts_delete" ON public."catalog_device_platter_counts" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_device_platter_counts_insert" ON public."catalog_device_platter_counts" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_platter_counts_update" ON public."catalog_device_platter_counts" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_roles_delete" ON public."catalog_device_roles" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_device_roles_insert" ON public."catalog_device_roles" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_roles_update" ON public."catalog_device_roles" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_types_delete" ON public."catalog_device_types" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_device_types_insert" ON public."catalog_device_types" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_device_types_update" ON public."catalog_device_types" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_donor_compatibility_matrix_delete" ON public."catalog_donor_compatibility_matrix" USING (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_donor_compatibility_matrix_insert" ON public."catalog_donor_compatibility_matrix" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_donor_compatibility_matrix_update" ON public."catalog_donor_compatibility_matrix" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_interfaces_delete" ON public."catalog_interfaces" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_interfaces_insert" ON public."catalog_interfaces" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_interfaces_update" ON public."catalog_interfaces" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_service_categories_delete" ON public."catalog_service_categories" USING (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_service_categories_insert" ON public."catalog_service_categories" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_service_categories_update" ON public."catalog_service_categories" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_service_line_items_delete" ON public."catalog_service_line_items" USING (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_service_line_items_insert" ON public."catalog_service_line_items" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_service_line_items_update" ON public."catalog_service_line_items" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "catalog_service_locations_delete" ON public."catalog_service_locations" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_service_locations_insert" ON public."catalog_service_locations" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_service_locations_update" ON public."catalog_service_locations" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_service_problems_delete" ON public."catalog_service_problems" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_service_problems_insert" ON public."catalog_service_problems" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_service_problems_update" ON public."catalog_service_problems" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_service_types_delete" ON public."catalog_service_types" USING (( SELECT is_admin() ));
ALTER POLICY "catalog_service_types_insert" ON public."catalog_service_types" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "catalog_service_types_update" ON public."catalog_service_types" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "chain_of_custody_business_unit_isolation" ON public."chain_of_custody" USING (((business_unit_id IS NULL) OR (( SELECT get_current_business_unit_id() ) IS NULL) OR (NOT ( SELECT business_unit_scoping_enabled() )) OR (business_unit_id = ( SELECT get_current_business_unit_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "chain_of_custody_tenant_isolation" ON public."chain_of_custody" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "chain_of_custody_access_log_tenant_isolation" ON public."chain_of_custody_access_log" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "chain_of_custody_integrity_checks_tenant_isolation" ON public."chain_of_custody_integrity_checks" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "chain_of_custody_transfers_tenant_isolation" ON public."chain_of_custody_transfers" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "clone_drives_delete" ON public."clone_drives" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "clone_drives_tenant_isolation" ON public."clone_drives" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "companies_delete" ON public."companies" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "companies_tenant_isolation" ON public."companies" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "company_documents_delete" ON public."company_documents" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "company_documents_tenant_isolation" ON public."company_documents" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "company_settings_delete" ON public."company_settings" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "company_settings_tenant_isolation" ON public."company_settings" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "coupon_redemptions_delete" ON public."coupon_redemptions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "coupon_redemptions_tenant_isolation" ON public."coupon_redemptions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "credit_note_allocations_delete" ON public."credit_note_allocations" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "credit_note_allocations_insert" ON public."credit_note_allocations" WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "credit_note_allocations_tenant_isolation" ON public."credit_note_allocations" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "credit_note_allocations_update" ON public."credit_note_allocations" USING (( SELECT has_role('accounts'::text) )) WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "credit_note_items_delete" ON public."credit_note_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "credit_note_items_insert" ON public."credit_note_items" WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "credit_note_items_tenant_isolation" ON public."credit_note_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "credit_note_items_update" ON public."credit_note_items" USING (( SELECT has_role('accounts'::text) )) WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "credit_notes_delete" ON public."credit_notes" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "credit_notes_insert" ON public."credit_notes" WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "credit_notes_tenant_isolation" ON public."credit_notes" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "credit_notes_update" ON public."credit_notes" USING (( SELECT has_role('accounts'::text) )) WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "customer_communications_delete" ON public."customer_communications" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "customer_communications_portal_read" ON public."customer_communications" USING (((deleted_at IS NULL) AND (customer_id = ( SELECT get_current_portal_customer_id() ))));
ALTER POLICY "customer_communications_tenant_isolation" ON public."customer_communications" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "customer_company_relationships_delete" ON public."customer_company_relationships" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "customer_company_relationships_tenant_isolation" ON public."customer_company_relationships" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "customer_groups_delete" ON public."customer_groups" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "customer_groups_tenant_isolation" ON public."customer_groups" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "customers_enhanced_delete" ON public."customers_enhanced" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "customers_enhanced_tenant_isolation" ON public."customers_enhanced" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "data_migration_entity_map_delete" ON public."data_migration_entity_map" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "data_migration_entity_map_insert" ON public."data_migration_entity_map" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "data_migration_entity_map_select" ON public."data_migration_entity_map" USING (( SELECT is_staff_user() ));
ALTER POLICY "data_migration_entity_map_tenant_isolation" ON public."data_migration_entity_map" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "data_migration_entity_map_update" ON public."data_migration_entity_map" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "data_migration_runs_delete" ON public."data_migration_runs" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "data_migration_runs_insert" ON public."data_migration_runs" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "data_migration_runs_select" ON public."data_migration_runs" USING (( SELECT is_staff_user() ));
ALTER POLICY "data_migration_runs_tenant_isolation" ON public."data_migration_runs" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "data_migration_runs_update" ON public."data_migration_runs" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "data_retention_policies_delete" ON public."data_retention_policies" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "data_retention_policies_insert" ON public."data_retention_policies" WITH CHECK (( SELECT has_role('admin'::text) ));
ALTER POLICY "data_retention_policies_tenant_isolation" ON public."data_retention_policies" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "data_retention_policies_update" ON public."data_retention_policies" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "data_subject_requests_delete" ON public."data_subject_requests" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "data_subject_requests_insert" ON public."data_subject_requests" WITH CHECK (( SELECT has_role('admin'::text) ));
ALTER POLICY "data_subject_requests_tenant_isolation" ON public."data_subject_requests" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "data_subject_requests_update" ON public."data_subject_requests" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "database_backups_delete" ON public."database_backups" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "database_backups_tenant_isolation" ON public."database_backups" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "departments_delete" ON public."departments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "departments_tenant_isolation" ON public."departments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "device_diagnostics_delete" ON public."device_diagnostics" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "device_diagnostics_tenant_isolation" ON public."device_diagnostics" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "document_instance_sections_delete" ON public."document_instance_sections" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "document_instance_sections_insert" ON public."document_instance_sections" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "document_instance_sections_tenant_isolation" ON public."document_instance_sections" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "document_instance_sections_update" ON public."document_instance_sections" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "document_instances_delete" ON public."document_instances" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "document_instances_insert" ON public."document_instances" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "document_instances_portal_read" ON public."document_instances" USING (((deleted_at IS NULL) AND (visible_to_customer = true) AND (status = ANY (ARRAY['delivered'::document_instance_status, 'signed_off'::document_instance_status])) AND (case_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM cases c
  WHERE ((c.id = document_instances.case_id) AND (c.customer_id = ( SELECT get_current_portal_customer_id() )))))));
ALTER POLICY "document_instances_tenant_isolation" ON public."document_instances" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "document_instances_update_authoring" ON public."document_instances" USING ((( SELECT is_staff_user() ) AND (status = ANY (ARRAY['draft'::document_instance_status, 'in_review'::document_instance_status])))) WITH CHECK ((( SELECT is_staff_user() ) AND (status = ANY (ARRAY['draft'::document_instance_status, 'in_review'::document_instance_status]))));
ALTER POLICY "document_signatures_insert" ON public."document_signatures" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "document_signatures_tenant_isolation" ON public."document_signatures" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "document_status_transitions_delete" ON public."document_status_transitions" USING (( SELECT is_platform_admin() ));
ALTER POLICY "document_status_transitions_insert" ON public."document_status_transitions" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "document_status_transitions_update" ON public."document_status_transitions" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "document_tax_lines_delete" ON public."document_tax_lines" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "document_tax_lines_insert" ON public."document_tax_lines" WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "document_tax_lines_select" ON public."document_tax_lines" USING (( SELECT is_staff_user() ));
ALTER POLICY "document_tax_lines_tenant_isolation" ON public."document_tax_lines" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "document_tax_lines_update" ON public."document_tax_lines" USING (( SELECT has_role('accounts'::text) ));
ALTER POLICY "document_template_versions_delete" ON public."document_template_versions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "document_template_versions_insert" ON public."document_template_versions" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "document_template_versions_tenant_isolation" ON public."document_template_versions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "document_template_versions_update" ON public."document_template_versions" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "document_templates_delete" ON public."document_templates" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "document_templates_tenant_isolation" ON public."document_templates" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "document_templates_pdf_delete" ON public."document_templates_pdf" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "document_templates_pdf_insert" ON public."document_templates_pdf" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "document_templates_pdf_tenant_isolation" ON public."document_templates_pdf" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "document_templates_pdf_update" ON public."document_templates_pdf" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "einvoice_submissions_insert" ON public."einvoice_submissions" WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "einvoice_submissions_select" ON public."einvoice_submissions" USING (( SELECT is_staff_user() ));
ALTER POLICY "einvoice_submissions_tenant_isolation" ON public."einvoice_submissions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "employee_documents_delete" ON public."employee_documents" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "employee_documents_tenant_isolation" ON public."employee_documents" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "employee_loans_delete" ON public."employee_loans" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "employee_loans_tenant_isolation" ON public."employee_loans" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "employee_salary_components_delete" ON public."employee_salary_components" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "employee_salary_components_tenant_isolation" ON public."employee_salary_components" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "employee_salary_config_delete" ON public."employee_salary_config" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "employee_salary_config_tenant_isolation" ON public."employee_salary_config" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "employee_salary_structures_delete" ON public."employee_salary_structures" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "employee_salary_structures_tenant_isolation" ON public."employee_salary_structures" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "employees_delete" ON public."employees" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "employees_tenant_isolation" ON public."employees" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "exchange_rates_delete" ON public."exchange_rates" USING (( SELECT is_platform_admin() ));
ALTER POLICY "exchange_rates_insert" ON public."exchange_rates" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "exchange_rates_update" ON public."exchange_rates" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "expense_attachments_delete" ON public."expense_attachments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "expense_attachments_tenant_isolation" ON public."expense_attachments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "expenses_delete" ON public."expenses" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "expenses_select" ON public."expenses" USING ((( SELECT is_staff_user() ) OR ( SELECT is_platform_admin() )));
ALTER POLICY "expenses_tenant_isolation" ON public."expenses" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "financial_audit_logs_tenant_isolation" ON public."financial_audit_logs" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "financial_transactions_insert" ON public."financial_transactions" WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "financial_transactions_select" ON public."financial_transactions" USING (( SELECT is_staff_user() ));
ALTER POLICY "financial_transactions_tenant_isolation" ON public."financial_transactions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "geo_cities_delete" ON public."geo_cities" USING (( SELECT is_platform_admin() ));
ALTER POLICY "geo_cities_insert" ON public."geo_cities" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "geo_cities_update" ON public."geo_cities" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "geo_countries_delete" ON public."geo_countries" USING (( SELECT is_platform_admin() ));
ALTER POLICY "geo_countries_insert" ON public."geo_countries" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "geo_countries_update" ON public."geo_countries" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "geo_country_tax_rates_delete" ON public."geo_country_tax_rates" USING (( SELECT is_platform_admin() ));
ALTER POLICY "geo_country_tax_rates_insert" ON public."geo_country_tax_rates" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "geo_country_tax_rates_update" ON public."geo_country_tax_rates" USING (( SELECT is_platform_admin() ));
ALTER POLICY "geo_languages_delete" ON public."geo_languages" USING (( SELECT is_platform_admin() ));
ALTER POLICY "geo_languages_insert" ON public."geo_languages" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "geo_languages_update" ON public."geo_languages" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "geo_regions_write" ON public."geo_regions" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "geo_subdivisions_write" ON public."geo_subdivisions" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "i18n_translations_delete" ON public."i18n_translations" USING (( SELECT is_platform_admin() ));
ALTER POLICY "i18n_translations_insert" ON public."i18n_translations" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "i18n_translations_update" ON public."i18n_translations" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "inventory_assignments_delete" ON public."inventory_assignments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_assignments_tenant_isolation" ON public."inventory_assignments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_case_assignments_delete" ON public."inventory_case_assignments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_case_assignments_tenant_isolation" ON public."inventory_case_assignments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_donor_parts_delete" ON public."inventory_donor_parts" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_donor_parts_insert" ON public."inventory_donor_parts" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "inventory_donor_parts_select" ON public."inventory_donor_parts" USING (( SELECT is_staff_user() ));
ALTER POLICY "inventory_donor_parts_tenant_isolation" ON public."inventory_donor_parts" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() ))) WITH CHECK (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_donor_parts_update" ON public."inventory_donor_parts" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "inventory_items_delete" ON public."inventory_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_items_tenant_isolation" ON public."inventory_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_locations_delete" ON public."inventory_locations" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_locations_tenant_isolation" ON public."inventory_locations" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_parts_usage_delete" ON public."inventory_parts_usage" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_parts_usage_tenant_isolation" ON public."inventory_parts_usage" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_photos_delete" ON public."inventory_photos" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_photos_tenant_isolation" ON public."inventory_photos" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_reservations_delete" ON public."inventory_reservations" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_reservations_tenant_isolation" ON public."inventory_reservations" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_search_templates_delete" ON public."inventory_search_templates" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_search_templates_tenant_isolation" ON public."inventory_search_templates" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_status_history_delete" ON public."inventory_status_history" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_status_history_tenant_isolation" ON public."inventory_status_history" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "inventory_transactions_delete" ON public."inventory_transactions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "inventory_transactions_tenant_isolation" ON public."inventory_transactions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "invoice_line_items_delete" ON public."invoice_line_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "invoice_line_items_tenant_isolation" ON public."invoice_line_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "invoices_business_unit_isolation" ON public."invoices" USING (((business_unit_id IS NULL) OR (( SELECT get_current_business_unit_id() ) IS NULL) OR (NOT ( SELECT business_unit_scoping_enabled() )) OR (business_unit_id = ( SELECT get_current_business_unit_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "invoices_delete" ON public."invoices" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "invoices_portal_read" ON public."invoices" USING (((deleted_at IS NULL) AND (customer_id = ( SELECT get_current_portal_customer_id() ))));
ALTER POLICY "invoices_tenant_isolation" ON public."invoices" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "kb_article_tags_delete" ON public."kb_article_tags" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "kb_article_tags_tenant_isolation" ON public."kb_article_tags" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "kb_article_versions_delete" ON public."kb_article_versions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "kb_article_versions_tenant_isolation" ON public."kb_article_versions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "kb_articles_delete" ON public."kb_articles" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "kb_articles_tenant_isolation" ON public."kb_articles" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "kb_categories_delete" ON public."kb_categories" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "kb_categories_tenant_isolation" ON public."kb_categories" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "kb_tags_delete" ON public."kb_tags" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "kb_tags_tenant_isolation" ON public."kb_tags" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "leave_balances_delete" ON public."leave_balances" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "leave_balances_tenant_isolation" ON public."leave_balances" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "leave_requests_delete" ON public."leave_requests" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "leave_requests_tenant_isolation" ON public."leave_requests" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "legal_entities_delete" ON public."legal_entities" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "legal_entities_tenant_isolation" ON public."legal_entities" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() ))) WITH CHECK (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "legal_entity_tax_registrations_delete" ON public."legal_entity_tax_registrations" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "legal_entity_tax_registrations_insert" ON public."legal_entity_tax_registrations" WITH CHECK (( SELECT is_tenant_admin() ));
ALTER POLICY "legal_entity_tax_registrations_select" ON public."legal_entity_tax_registrations" USING (( SELECT is_staff_user() ));
ALTER POLICY "legal_entity_tax_registrations_tenant_isolation" ON public."legal_entity_tax_registrations" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "legal_entity_tax_registrations_update" ON public."legal_entity_tax_registrations" USING (( SELECT is_tenant_admin() ));
ALTER POLICY "loan_repayments_delete" ON public."loan_repayments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "loan_repayments_tenant_isolation" ON public."loan_repayments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "master_case_no_solution_reasons_delete" ON public."master_case_no_solution_reasons" USING (( SELECT is_admin() ));
ALTER POLICY "master_case_no_solution_reasons_insert" ON public."master_case_no_solution_reasons" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_case_no_solution_reasons_update" ON public."master_case_no_solution_reasons" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_case_priorities_delete" ON public."master_case_priorities" USING (( SELECT is_admin() ));
ALTER POLICY "master_case_priorities_insert" ON public."master_case_priorities" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_case_priorities_update" ON public."master_case_priorities" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_case_statuses_delete" ON public."master_case_statuses" USING (( SELECT is_admin() ));
ALTER POLICY "master_case_statuses_insert" ON public."master_case_statuses" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_case_statuses_update" ON public."master_case_statuses" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_country_pack_tests_delete" ON public."master_country_pack_tests" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_country_pack_tests_insert" ON public."master_country_pack_tests" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_country_pack_tests_update" ON public."master_country_pack_tests" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_country_pack_versions_delete" ON public."master_country_pack_versions" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_country_pack_versions_insert" ON public."master_country_pack_versions" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_country_pack_versions_update" ON public."master_country_pack_versions" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_currency_codes_delete" ON public."master_currency_codes" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_currency_codes_insert" ON public."master_currency_codes" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_currency_codes_update" ON public."master_currency_codes" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "mdrr_write" ON public."master_data_residency_regions" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_document_requirements_platform_write" ON public."master_document_requirements" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_einvoice_regimes_delete" ON public."master_einvoice_regimes" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_einvoice_regimes_insert" ON public."master_einvoice_regimes" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_einvoice_regimes_update" ON public."master_einvoice_regimes" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_engine_capabilities_delete" ON public."master_engine_capabilities" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_engine_capabilities_insert" ON public."master_engine_capabilities" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_engine_capabilities_update" ON public."master_engine_capabilities" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_expense_categories_delete" ON public."master_expense_categories" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_expense_categories_insert" ON public."master_expense_categories" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_expense_categories_update" ON public."master_expense_categories" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_industries_delete" ON public."master_industries" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_industries_insert" ON public."master_industries" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_industries_update" ON public."master_industries" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_inventory_categories_delete" ON public."master_inventory_categories" USING (( SELECT is_admin() ));
ALTER POLICY "master_inventory_categories_insert" ON public."master_inventory_categories" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_inventory_categories_update" ON public."master_inventory_categories" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_inventory_condition_types_delete" ON public."master_inventory_condition_types" USING (( SELECT is_admin() ));
ALTER POLICY "master_inventory_condition_types_insert" ON public."master_inventory_condition_types" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_inventory_condition_types_update" ON public."master_inventory_condition_types" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_inventory_item_categories_delete" ON public."master_inventory_item_categories" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_inventory_item_categories_insert" ON public."master_inventory_item_categories" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_inventory_item_categories_update" ON public."master_inventory_item_categories" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_inventory_status_types_delete" ON public."master_inventory_status_types" USING (( SELECT is_admin() ));
ALTER POLICY "master_inventory_status_types_insert" ON public."master_inventory_status_types" WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_inventory_status_types_update" ON public."master_inventory_status_types" USING (( SELECT is_admin() )) WITH CHECK (( SELECT is_admin() ));
ALTER POLICY "master_invoice_statuses_delete" ON public."master_invoice_statuses" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_invoice_statuses_insert" ON public."master_invoice_statuses" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_invoice_statuses_update" ON public."master_invoice_statuses" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_leave_types_delete" ON public."master_leave_types" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_leave_types_insert" ON public."master_leave_types" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_leave_types_update" ON public."master_leave_types" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_modules_delete" ON public."master_modules" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_modules_insert" ON public."master_modules" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_modules_update" ON public."master_modules" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_notification_templates_delete" ON public."master_notification_templates" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_notification_templates_insert" ON public."master_notification_templates" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_notification_templates_update" ON public."master_notification_templates" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_numbering_policies_write" ON public."master_numbering_policies" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_payment_methods_delete" ON public."master_payment_methods" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_payment_methods_insert" ON public."master_payment_methods" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_payment_methods_update" ON public."master_payment_methods" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_payroll_components_delete" ON public."master_payroll_components" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_payroll_components_insert" ON public."master_payroll_components" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_payroll_components_update" ON public."master_payroll_components" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_purchase_order_statuses_delete" ON public."master_purchase_order_statuses" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_purchase_order_statuses_insert" ON public."master_purchase_order_statuses" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_purchase_order_statuses_update" ON public."master_purchase_order_statuses" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_quote_statuses_delete" ON public."master_quote_statuses" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_quote_statuses_insert" ON public."master_quote_statuses" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_quote_statuses_update" ON public."master_quote_statuses" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_supplier_categories_delete" ON public."master_supplier_categories" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_supplier_categories_insert" ON public."master_supplier_categories" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_supplier_categories_update" ON public."master_supplier_categories" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_supplier_payment_terms_delete" ON public."master_supplier_payment_terms" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_supplier_payment_terms_insert" ON public."master_supplier_payment_terms" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_supplier_payment_terms_update" ON public."master_supplier_payment_terms" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_template_categories_delete" ON public."master_template_categories" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_template_categories_insert" ON public."master_template_categories" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_template_categories_update" ON public."master_template_categories" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_template_types_delete" ON public."master_template_types" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_template_types_insert" ON public."master_template_types" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_template_types_update" ON public."master_template_types" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_template_variables_delete" ON public."master_template_variables" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_template_variables_insert" ON public."master_template_variables" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_template_variables_update" ON public."master_template_variables" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_transaction_categories_delete" ON public."master_transaction_categories" USING (( SELECT is_platform_admin() ));
ALTER POLICY "master_transaction_categories_insert" ON public."master_transaction_categories" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_transaction_categories_update" ON public."master_transaction_categories" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "master_unit_codes_platform_write" ON public."master_unit_codes" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "ndas_delete" ON public."ndas" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "ndas_tenant_isolation" ON public."ndas" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "notification_events_delete" ON public."notification_events" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "notification_events_tenant_isolation" ON public."notification_events" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "notification_log_delete" ON public."notification_log" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "notification_log_select" ON public."notification_log" USING (((recipient_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT has_role('admin'::text) )));
ALTER POLICY "notification_log_tenant_isolation" ON public."notification_log" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "notification_log_update" ON public."notification_log" USING (((recipient_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT has_role('admin'::text) )));
ALTER POLICY "notification_subscriptions_delete" ON public."notification_subscriptions" USING (((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT has_role('admin'::text) )));
ALTER POLICY "notification_subscriptions_insert" ON public."notification_subscriptions" WITH CHECK (((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT has_role('admin'::text) )));
ALTER POLICY "notification_subscriptions_select" ON public."notification_subscriptions" USING (((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT has_role('admin'::text) )));
ALTER POLICY "notification_subscriptions_tenant_isolation" ON public."notification_subscriptions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "notification_subscriptions_update" ON public."notification_subscriptions" USING (((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT has_role('admin'::text) )));
ALTER POLICY "notification_templates_delete" ON public."notification_templates" USING ((((tenant_id IS NULL) AND ( SELECT is_platform_admin() )) OR ((tenant_id = ( SELECT get_current_tenant_id() )) AND ( SELECT has_role('admin'::text) ))));
ALTER POLICY "notification_templates_insert" ON public."notification_templates" WITH CHECK ((((tenant_id IS NULL) AND ( SELECT is_platform_admin() )) OR ((tenant_id = ( SELECT get_current_tenant_id() )) AND ( SELECT has_role('admin'::text) ))));
ALTER POLICY "notification_templates_tenant_isolation" ON public."notification_templates" USING (((tenant_id IS NULL) OR (tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "notification_templates_update" ON public."notification_templates" USING ((((tenant_id IS NULL) AND ( SELECT is_platform_admin() )) OR ((tenant_id = ( SELECT get_current_tenant_id() )) AND ( SELECT has_role('admin'::text) )))) WITH CHECK ((((tenant_id IS NULL) AND ( SELECT is_platform_admin() )) OR ((tenant_id = ( SELECT get_current_tenant_id() )) AND ( SELECT has_role('admin'::text) ))));
ALTER POLICY "notification_webhooks_delete" ON public."notification_webhooks" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "notification_webhooks_insert" ON public."notification_webhooks" WITH CHECK (( SELECT has_role('admin'::text) ));
ALTER POLICY "notification_webhooks_tenant_isolation" ON public."notification_webhooks" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "notification_webhooks_update" ON public."notification_webhooks" USING (( SELECT has_role('admin'::text) )) WITH CHECK (( SELECT has_role('admin'::text) ));
ALTER POLICY "number_sequences_business_unit_isolation" ON public."number_sequences" USING (((business_unit_id IS NULL) OR (( SELECT get_current_business_unit_id() ) IS NULL) OR (NOT ( SELECT business_unit_scoping_enabled() )) OR (business_unit_id = ( SELECT get_current_business_unit_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "number_sequences_delete" ON public."number_sequences" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "number_sequences_tenant_isolation" ON public."number_sequences" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "number_sequences_audit_tenant_isolation" ON public."number_sequences_audit" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "onboarding_checklist_items_delete" ON public."onboarding_checklist_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "onboarding_checklist_items_tenant_isolation" ON public."onboarding_checklist_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "onboarding_checklists_delete" ON public."onboarding_checklists" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "onboarding_checklists_tenant_isolation" ON public."onboarding_checklists" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "onboarding_progress_tenant_isolation" ON public."onboarding_progress" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "onboarding_tasks_delete" ON public."onboarding_tasks" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "onboarding_tasks_tenant_isolation" ON public."onboarding_tasks" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payment_allocations_delete" ON public."payment_allocations" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payment_allocations_tenant_isolation" ON public."payment_allocations" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payment_disbursements_delete" ON public."payment_disbursements" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payment_disbursements_tenant_isolation" ON public."payment_disbursements" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payment_receipts_delete" ON public."payment_receipts" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payment_receipts_tenant_isolation" ON public."payment_receipts" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payment_withholdings_delete" ON public."payment_withholdings" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payment_withholdings_insert" ON public."payment_withholdings" WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "payment_withholdings_select" ON public."payment_withholdings" USING (( SELECT is_staff_user() ));
ALTER POLICY "payment_withholdings_tenant_isolation" ON public."payment_withholdings" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payment_withholdings_update" ON public."payment_withholdings" USING (( SELECT has_role('accounts'::text) ));
ALTER POLICY "payments_delete" ON public."payments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payments_portal_read" ON public."payments" USING (((deleted_at IS NULL) AND (customer_id = ( SELECT get_current_portal_customer_id() ))));
ALTER POLICY "payments_tenant_isolation" ON public."payments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payroll_adjustments_delete" ON public."payroll_adjustments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payroll_adjustments_tenant_isolation" ON public."payroll_adjustments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payroll_bank_files_delete" ON public."payroll_bank_files" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payroll_bank_files_tenant_isolation" ON public."payroll_bank_files" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payroll_periods_delete" ON public."payroll_periods" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payroll_periods_tenant_isolation" ON public."payroll_periods" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payroll_record_items_delete" ON public."payroll_record_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payroll_record_items_tenant_isolation" ON public."payroll_record_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payroll_records_delete" ON public."payroll_records" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payroll_records_tenant_isolation" ON public."payroll_records" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "payroll_settings_delete" ON public."payroll_settings" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "payroll_settings_tenant_isolation" ON public."payroll_settings" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "pdf_generation_logs_delete" ON public."pdf_generation_logs" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "pdf_generation_logs_tenant_isolation" ON public."pdf_generation_logs" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "performance_reviews_delete" ON public."performance_reviews" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "performance_reviews_tenant_isolation" ON public."performance_reviews" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "plan_features_delete" ON public."plan_features" USING (( SELECT is_platform_admin() ));
ALTER POLICY "plan_features_insert" ON public."plan_features" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "plan_features_update" ON public."plan_features" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "platform_admins_platform_only" ON public."platform_admins" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "platform_announcements_delete" ON public."platform_announcements" USING (( SELECT is_platform_admin() ));
ALTER POLICY "platform_announcements_insert" ON public."platform_announcements" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "platform_announcements_select" ON public."platform_announcements" USING (((is_active = true) OR ( SELECT is_platform_admin() )));
ALTER POLICY "platform_announcements_update" ON public."platform_announcements" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "platform_audit_logs_platform_only" ON public."platform_audit_logs" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "platform_audit_logs_platform_only_restrictive" ON public."platform_audit_logs" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "platform_metrics_platform_only" ON public."platform_metrics" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "platform_tenant_code_prefixes_admin_all" ON public."platform_tenant_code_prefixes" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "platform_tenant_code_sequences_admin_all" ON public."platform_tenant_code_sequences" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "portal_link_history_delete" ON public."portal_link_history" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "portal_link_history_tenant_isolation" ON public."portal_link_history" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "positions_delete" ON public."positions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "positions_tenant_isolation" ON public."positions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "profiles_delete" ON public."profiles" USING (( SELECT is_platform_admin() ));
ALTER POLICY "profiles_select" ON public."profiles" USING (((id = ( SELECT auth.uid() AS uid)) OR (tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "profiles_tenant_isolation" ON public."profiles" USING (((id = ( SELECT auth.uid() AS uid)) OR (tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() ))) WITH CHECK (((id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_platform_admin() )));
ALTER POLICY "profiles_update" ON public."profiles" USING (((id = ( SELECT auth.uid() AS uid)) OR ((tenant_id = ( SELECT get_current_tenant_id() )) AND ( SELECT has_role('admin'::text) )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "purchase_order_items_delete" ON public."purchase_order_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "purchase_order_items_tenant_isolation" ON public."purchase_order_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "purchase_orders_delete" ON public."purchase_orders" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "purchase_orders_tenant_isolation" ON public."purchase_orders" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "quote_history_delete" ON public."quote_history" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "quote_history_tenant_isolation" ON public."quote_history" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "quote_items_delete" ON public."quote_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "quote_items_tenant_isolation" ON public."quote_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "quotes_business_unit_isolation" ON public."quotes" USING (((business_unit_id IS NULL) OR (( SELECT get_current_business_unit_id() ) IS NULL) OR (NOT ( SELECT business_unit_scoping_enabled() )) OR (business_unit_id = ( SELECT get_current_business_unit_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "quotes_delete" ON public."quotes" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "quotes_portal_read" ON public."quotes" USING (((deleted_at IS NULL) AND (customer_id = ( SELECT get_current_portal_customer_id() ))));
ALTER POLICY "quotes_tenant_isolation" ON public."quotes" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "receipt_allocations_delete" ON public."receipt_allocations" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "receipt_allocations_tenant_isolation" ON public."receipt_allocations" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "receipts_delete" ON public."receipts" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "receipts_tenant_isolation" ON public."receipts" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "reconciliation_matches_delete" ON public."reconciliation_matches" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "reconciliation_matches_tenant_isolation" ON public."reconciliation_matches" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "recovery_manifest_acceptances_insert" ON public."recovery_manifest_acceptances" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "recovery_manifest_acceptances_tenant_isolation" ON public."recovery_manifest_acceptances" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "recovery_manifest_items_delete" ON public."recovery_manifest_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "recovery_manifest_items_insert" ON public."recovery_manifest_items" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "recovery_manifest_items_tenant_isolation" ON public."recovery_manifest_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "recovery_manifest_items_update" ON public."recovery_manifest_items" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "recovery_manifests_delete" ON public."recovery_manifests" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "recovery_manifests_insert" ON public."recovery_manifests" WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "recovery_manifests_tenant_isolation" ON public."recovery_manifests" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "recovery_manifests_update" ON public."recovery_manifests" USING (( SELECT is_staff_user() )) WITH CHECK (( SELECT is_staff_user() ));
ALTER POLICY "recruitment_candidates_delete" ON public."recruitment_candidates" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "recruitment_candidates_tenant_isolation" ON public."recruitment_candidates" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "recruitment_jobs_delete" ON public."recruitment_jobs" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "recruitment_jobs_tenant_isolation" ON public."recruitment_jobs" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "resource_clone_drives_delete" ON public."resource_clone_drives" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "resource_clone_drives_tenant_isolation" ON public."resource_clone_drives" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "role_module_permissions_delete" ON public."role_module_permissions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "role_module_permissions_tenant_isolation" ON public."role_module_permissions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "salary_components_delete" ON public."salary_components" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "salary_components_tenant_isolation" ON public."salary_components" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_adjustment_session_items_delete" ON public."stock_adjustment_session_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_adjustment_session_items_tenant_isolation" ON public."stock_adjustment_session_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_adjustment_sessions_delete" ON public."stock_adjustment_sessions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_adjustment_sessions_tenant_isolation" ON public."stock_adjustment_sessions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_adjustments_delete" ON public."stock_adjustments" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_adjustments_tenant_isolation" ON public."stock_adjustments" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_alerts_delete" ON public."stock_alerts" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_alerts_tenant_isolation" ON public."stock_alerts" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_categories_delete" ON public."stock_categories" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_categories_tenant_isolation" ON public."stock_categories" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_items_delete" ON public."stock_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_items_tenant_isolation" ON public."stock_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_locations_delete" ON public."stock_locations" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_locations_tenant_isolation" ON public."stock_locations" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_movements_delete" ON public."stock_movements" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_movements_tenant_isolation" ON public."stock_movements" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_price_history_delete" ON public."stock_price_history" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_price_history_tenant_isolation" ON public."stock_price_history" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_sale_items_delete" ON public."stock_sale_items" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_sale_items_tenant_isolation" ON public."stock_sale_items" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_sales_delete" ON public."stock_sales" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_sales_portal_read" ON public."stock_sales" USING (((deleted_at IS NULL) AND (customer_id = ( SELECT get_current_portal_customer_id() ))));
ALTER POLICY "stock_sales_tenant_isolation" ON public."stock_sales" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_serial_numbers_delete" ON public."stock_serial_numbers" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_serial_numbers_tenant_isolation" ON public."stock_serial_numbers" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "stock_transactions_delete" ON public."stock_transactions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "stock_transactions_tenant_isolation" ON public."stock_transactions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "subscription_plans_delete" ON public."subscription_plans" USING (( SELECT is_platform_admin() ));
ALTER POLICY "subscription_plans_insert" ON public."subscription_plans" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "subscription_plans_update" ON public."subscription_plans" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "supplier_audit_trail_delete" ON public."supplier_audit_trail" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "supplier_audit_trail_tenant_isolation" ON public."supplier_audit_trail" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "supplier_communications_delete" ON public."supplier_communications" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "supplier_communications_tenant_isolation" ON public."supplier_communications" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "supplier_contacts_delete" ON public."supplier_contacts" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "supplier_contacts_tenant_isolation" ON public."supplier_contacts" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "supplier_documents_delete" ON public."supplier_documents" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "supplier_documents_tenant_isolation" ON public."supplier_documents" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "supplier_performance_metrics_delete" ON public."supplier_performance_metrics" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "supplier_performance_metrics_tenant_isolation" ON public."supplier_performance_metrics" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "supplier_products_delete" ON public."supplier_products" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "supplier_products_tenant_isolation" ON public."supplier_products" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "suppliers_delete" ON public."suppliers" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "suppliers_tenant_isolation" ON public."suppliers" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "support_ticket_messages_insert" ON public."support_ticket_messages" WITH CHECK ((EXISTS ( SELECT 1
   FROM support_tickets st
  WHERE ((st.id = support_ticket_messages.ticket_id) AND ((st.tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() ))))));
ALTER POLICY "support_ticket_messages_select" ON public."support_ticket_messages" USING ((EXISTS ( SELECT 1
   FROM support_tickets st
  WHERE ((st.id = support_ticket_messages.ticket_id) AND ((st.tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() ))))));
ALTER POLICY "support_tickets_delete" ON public."support_tickets" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "support_tickets_tenant_isolation" ON public."support_tickets" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "system_logs_delete" ON public."system_logs" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "system_logs_tenant_isolation" ON public."system_logs" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "system_seed_status_delete" ON public."system_seed_status" USING (( SELECT is_platform_admin() ));
ALTER POLICY "system_seed_status_insert" ON public."system_seed_status" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "system_seed_status_update" ON public."system_seed_status" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "system_settings_delete" ON public."system_settings" USING (( SELECT is_platform_admin() ));
ALTER POLICY "system_settings_insert" ON public."system_settings" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "system_settings_update" ON public."system_settings" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "system_settings_internal_admin" ON public."system_settings_internal" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "tax_rates_delete" ON public."tax_rates" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "tax_rates_tenant_isolation" ON public."tax_rates" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tax_return_lines_delete" ON public."tax_return_lines" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "tax_return_lines_insert" ON public."tax_return_lines" WITH CHECK (( SELECT has_role('accounts'::text) ));
ALTER POLICY "tax_return_lines_select" ON public."tax_return_lines" USING (( SELECT is_staff_user() ));
ALTER POLICY "tax_return_lines_tenant_isolation" ON public."tax_return_lines" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tax_return_lines_update" ON public."tax_return_lines" USING (( SELECT has_role('accounts'::text) ));
ALTER POLICY "template_versions_delete" ON public."template_versions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "template_versions_tenant_isolation" ON public."template_versions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "templates_delete" ON public."templates" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "templates_tenant_isolation" ON public."templates" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenant_activity_log_delete" ON public."tenant_activity_log" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "tenant_activity_log_tenant_isolation" ON public."tenant_activity_log" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenant_currencies_delete" ON public."tenant_currencies" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "tenant_currencies_tenant_isolation" ON public."tenant_currencies" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenant_device_type_settings_delete" ON public."tenant_device_type_settings" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "tenant_device_type_settings_insert" ON public."tenant_device_type_settings" WITH CHECK (( SELECT has_role('manager'::text) ));
ALTER POLICY "tenant_device_type_settings_select" ON public."tenant_device_type_settings" USING (( SELECT is_staff_user() ));
ALTER POLICY "tenant_device_type_settings_tenant_isolation" ON public."tenant_device_type_settings" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() ))) WITH CHECK (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenant_device_type_settings_update" ON public."tenant_device_type_settings" USING (( SELECT has_role('manager'::text) )) WITH CHECK (( SELECT has_role('manager'::text) ));
ALTER POLICY "tenant_health_metrics_delete" ON public."tenant_health_metrics" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "tenant_health_metrics_tenant_isolation" ON public."tenant_health_metrics" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenant_impersonation_sessions_platform_only" ON public."tenant_impersonation_sessions" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "tenant_payment_methods_delete" ON public."tenant_payment_methods" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "tenant_payment_methods_tenant_isolation" ON public."tenant_payment_methods" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenant_rate_limits_delete" ON public."tenant_rate_limits" USING (( SELECT is_platform_admin() ));
ALTER POLICY "tenant_rate_limits_insert" ON public."tenant_rate_limits" WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "tenant_rate_limits_select" ON public."tenant_rate_limits" USING (((deleted_at IS NULL) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenant_rate_limits_tenant_isolation" ON public."tenant_rate_limits" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenant_rate_limits_update" ON public."tenant_rate_limits" USING (( SELECT is_platform_admin() )) WITH CHECK (( SELECT is_platform_admin() ));
ALTER POLICY "tenant_sla_policies_delete" ON public."tenant_sla_policies" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "tenant_sla_policies_insert" ON public."tenant_sla_policies" WITH CHECK (( SELECT has_role('admin'::text) ));
ALTER POLICY "tenant_sla_policies_tenant_isolation" ON public."tenant_sla_policies" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenant_sla_policies_update" ON public."tenant_sla_policies" USING (( SELECT has_role('admin'::text) )) WITH CHECK (( SELECT has_role('admin'::text) ));
ALTER POLICY "tenant_subscriptions_delete" ON public."tenant_subscriptions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "tenant_subscriptions_tenant_isolation" ON public."tenant_subscriptions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenants_delete" ON public."tenants" USING (( SELECT is_platform_admin() ));
ALTER POLICY "tenants_select" ON public."tenants" USING (((id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "tenants_update" ON public."tenants" USING ((((id = ( SELECT get_current_tenant_id() )) AND ( SELECT has_role('admin'::text) )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "timesheets_delete" ON public."timesheets" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "timesheets_tenant_isolation" ON public."timesheets" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "usage_records_delete" ON public."usage_records" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "usage_records_tenant_isolation" ON public."usage_records" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "usage_snapshots_delete" ON public."usage_snapshots" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "usage_snapshots_tenant_isolation" ON public."usage_snapshots" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "user_activity_logs_delete" ON public."user_activity_logs" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "user_activity_logs_tenant_isolation" ON public."user_activity_logs" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "user_activity_sessions_delete" ON public."user_activity_sessions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "user_activity_sessions_tenant_isolation" ON public."user_activity_sessions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "user_preferences_delete" ON public."user_preferences" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "user_preferences_tenant_isolation" ON public."user_preferences" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "user_sessions_delete" ON public."user_sessions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "user_sessions_tenant_isolation" ON public."user_sessions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "user_sidebar_preferences_delete" ON public."user_sidebar_preferences" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "user_sidebar_preferences_tenant_isolation" ON public."user_sidebar_preferences" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "vat_records_delete" ON public."vat_records" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "vat_records_tenant_isolation" ON public."vat_records" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "vat_returns_delete" ON public."vat_returns" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "vat_returns_tenant_isolation" ON public."vat_returns" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
ALTER POLICY "vat_transactions_delete" ON public."vat_transactions" USING (( SELECT has_role('admin'::text) ));
ALTER POLICY "vat_transactions_tenant_isolation" ON public."vat_transactions" USING (((tenant_id = ( SELECT get_current_tenant_id() )) OR ( SELECT is_platform_admin() )));
