// scripts/localization/parity-replay.test.ts
//
// M-E PARITY REPLAY — permanent regression gate: the fiscal kernel must reproduce
// the STORED subtotal/tax_amount/total_amount of every live invoice and quote,
// except a committed allowlist of pre-cutover historical artifacts.
//
// WHY AN ALLOWLIST. The exit gate (a prior investigation) already proved the kernel
// is byte-identical to the now-deleted legacy calculateInvoiceTotals/QuoteTotals on
// the full corpus. This harness is the stricter, longer-lived check: kernel-vs-STORED.
// The stored figures were written over years by legacy code and hand edits, so a
// minority carry artifacts that NO correct kernel can reproduce from their own inputs.
// Every such document is enumerated in ./parity-replay-allowlist.json. The three
// documented classes (generated by replaying the kernel over the entire live corpus —
// 2131 docs, 106 divergences — see the run recorded in the migration/handoff notes):
//
//   1. historical_precision_drift (65) — OMR (3dp) docs whose stored tax was computed
//      at the old 2-decimal precision or with a back-solved odd rate (4.97 / 4.99 /
//      5.01 / 5.04 / 5.05). The kernel computes at the currency-native 3dp, so tax
//      differs by <= 0.005 OMR. Subtotal (Sigma line items) still reconstructs exactly.
//   2. bad_data (40) — stored figures that cannot be reconstructed from the stored
//      inputs: either stored subtotal != Sigma(reconstructed line items) [18], or tax
//      omitted despite a non-zero rate — legacy quotes saved with tax_amount = 0 and
//      total = subtotal - discount, i.e. VAT never applied [22].
//   3. float_ordering_artifact (1) — quote b2d6ccec, owner-approved, differs by 1 mil
//      due to a legacy floating-point ordering artifact (kernel 1.428 vs stored 1.43).
//
// NEW post-cutover documents are written THROUGH the kernel, so they match by
// construction and never enter this allowlist. If a NEW divergence appears outside the
// allowlist, this test fails — that is the regression it guards. If the divergence is a
// genuine new historical artifact, add it (with a reason) to the allowlist; otherwise
// it is a real kernel/service regression to fix.
//
// Runs only when SUPABASE_DB_URL is set (CI, via psql); self-skips locally.
import { describe, it, expect } from 'vitest';
import { execSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { computeDocumentTax } from '../../src/lib/tax/kernel';
import { buildTaxableLines, matchFormRate, totalsFromComputation } from '../../src/lib/taxDocumentService';
import type { GeoCountryTaxRateRow, TaxContext } from '../../src/lib/regimes/types';

const DB = process.env.SUPABASE_DB_URL;

interface AllowlistEntry { id: string; kind: 'invoice' | 'quote'; reason: string }
const ALLOWLIST: AllowlistEntry[] = JSON.parse(
  readFileSync(new URL('./parity-replay-allowlist.json', import.meta.url), 'utf8'),
) as AllowlistEntry[];
const ALLOWED = new Set(ALLOWLIST.map((e) => e.id));
const allowlistByReason = ALLOWLIST.reduce<Record<string, number>>((acc, e) => {
  acc[e.reason] = (acc[e.reason] ?? 0) + 1; return acc;
}, {});

interface DocRow {
  id: string; currency: string; decimals: number; tax_rate: number;
  discount_amount: number; discount_type: string | null;
  subtotal: number; tax_amount: number; total_amount: number;
  items: Array<{ description: string; quantity: number; unit_price: number; discount_percent: number }>;
  rates: GeoCountryTaxRateRow[];
}

function fetchDocs(kind: 'invoice' | 'quote'): DocRow[] {
  const table = kind === 'invoice' ? 'invoices' : 'quotes';
  const itemTable = kind === 'invoice' ? 'invoice_line_items' : 'quote_items';
  const fk = kind === 'invoice' ? 'invoice_id' : 'quote_id';
  // Both line-item tables store the per-line percentage discount in a column named
  // `discount` (invoice_line_items has no `discount_percent` column). buildTaxableLines
  // reads it as discount_percent.
  const discountCol = 'd.discount';
  // Header date column is kind-aware: invoices carry invoice_date, quotes carry
  // quote_date (quotes have no invoice_date column). COALESCE→CURRENT_DATE covers nulls.
  const dateCol = kind === 'invoice' ? 'h.invoice_date' : 'h.quote_date';
  // One JSON blob per document with its LIVE items (soft-deleted rows excluded, matching
  // the services' persist path) and the effective OM standard rate rows.
  const sql = `
    SELECT json_agg(row) FROM (
      SELECT json_build_object(
        'id', h.id, 'currency', COALESCE(h.currency,'OMR'),
        'decimals', COALESCE(mc.decimal_places, 3), 'tax_rate', COALESCE(h.tax_rate,0),
        'discount_amount', COALESCE(h.discount_amount,0),
        'discount_type', ${kind === 'quote' ? 'h.discount_type' : 'NULL'},
        'subtotal', COALESCE(h.subtotal,0), 'tax_amount', COALESCE(h.tax_amount,0),
        'total_amount', COALESCE(h.total_amount,0),
        'items', COALESCE((SELECT json_agg(json_build_object(
            'description', d.description, 'quantity', d.quantity, 'unit_price', d.unit_price,
            'discount_percent', COALESCE(${discountCol},0)) ORDER BY d.sort_order)
          FROM ${itemTable} d WHERE d.${fk} = h.id AND d.deleted_at IS NULL), '[]'::json),
        'rates', COALESCE((SELECT json_agg(json_build_object(
            'id', r.id, 'country_id', r.country_id, 'subdivision_id', r.subdivision_id,
            'component_code', r.component_code, 'component_label', r.component_label,
            'tax_category', r.tax_category, 'rate', r.rate, 'applies_to', r.applies_to,
            'valid_from', r.valid_from, 'valid_to', r.valid_to, 'sort_order', r.sort_order))
          FROM geo_country_tax_rates r
          JOIN legal_entities le ON le.id = (SELECT id FROM legal_entities WHERE tenant_id = h.tenant_id AND is_primary LIMIT 1)
          WHERE r.country_id = le.country_id AND r.tax_category='standard' AND r.subdivision_id IS NULL
            AND r.valid_from <= COALESCE(${dateCol}, CURRENT_DATE)
            AND (r.valid_to IS NULL OR r.valid_to >= COALESCE(${dateCol}, CURRENT_DATE))
            AND r.deleted_at IS NULL), '[]'::json)
      ) AS row
      FROM ${table} h
      LEFT JOIN master_currency_codes mc ON mc.code = h.currency
      WHERE h.deleted_at IS NULL
    ) s`;
  const out = execSync(`psql "${DB}" -t -A -c "${sql.replace(/\n/g, ' ')}"`, { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024 }).trim();
  return out && out !== '' ? JSON.parse(out) : [];
}

function replay(doc: DocRow, kind: 'invoice' | 'quote'): { subtotal: number; taxAmount: number; totalAmount: number } {
  const rates = matchFormRate(doc.rates, doc.tax_rate);
  const lines = buildTaxableLines(doc.items, doc.decimals);
  // The kernel's documentDiscount is a MONEY value; the cutover services (taxDocumentService
  // .computeDocumentTotals, fed by invoiceService/quotesService) convert any percentage to
  // money before the kernel. For the stored corpus that money value is already what sits in
  // discount_amount (invoices always store money; quotes with discount_type='percentage'
  // store the resolved money amount, verified on the live corpus), so we feed it directly —
  // regardless of discount_type. (The previous version recomputed subtotal*discount_amount/100,
  // double-applying the percentage.)
  const documentDiscount = doc.discount_amount;
  const ctx: TaxContext = {
    documentType: kind,
    seller: { legalEntityId: 'x', countryId: doc.rates[0]?.country_id ?? 'x', subdivisionId: null, taxIdentifier: null, registrations: [] },
    buyer: { taxNumber: null, countryId: null, subdivisionId: null, isBusiness: false, addressSnapshot: null },
    taxPointDate: '2026-07-02', placeOfSupplySubdivisionId: null,
    lines: rates.length === 0 ? lines.map((l) => ({ ...l, treatment: 'out_of_scope' as const })) : lines,
    documentDiscount, taxInclusive: false,
    rateContext: { documentCurrency: doc.currency, documentDecimals: doc.decimals, baseCurrency: doc.currency, baseDecimals: doc.decimals, rate: 1, rateSource: 'derived' },
    rates,
    roundingPolicy: { mode: 'half_up', level: 'document' }, scaleSystem: 'western',
  };
  const c = computeDocumentTax(ctx);
  return totalsFromComputation(c, documentDiscount, doc.decimals);
}

interface Divergence { id: string; kind: 'invoice' | 'quote'; field: string; stored: number; kernel: number }

describe.skipIf(!DB)('M-E parity replay — kernel reproduces the stored corpus modulo the committed allowlist', () => {
  it('every kernel-vs-stored divergence is a documented historical artifact', () => {
    const divergences: Divergence[] = [];
    for (const kind of ['invoice', 'quote'] as const) {
      const docs = fetchDocs(kind);
      expect(docs.length, `${kind} corpus should be non-empty`).toBeGreaterThan(0);
      for (const doc of docs) {
        const r = replay(doc, kind);
        if (r.taxAmount !== doc.tax_amount) divergences.push({ id: doc.id, kind, field: 'tax', stored: doc.tax_amount, kernel: r.taxAmount });
        if (r.totalAmount !== doc.total_amount) divergences.push({ id: doc.id, kind, field: 'total', stored: doc.total_amount, kernel: r.totalAmount });
        if (r.subtotal !== doc.subtotal) divergences.push({ id: doc.id, kind, field: 'subtotal', stored: doc.subtotal, kernel: r.subtotal });
      }
    }

    const unexpected = divergences.filter((d) => !ALLOWED.has(d.id));
    const unexpectedIds = [...new Set(unexpected.map((d) => `${d.kind}:${d.id}`))];
    const divergentIds = [...new Set(divergences.map((d) => d.id))];
    const message =
      `\n${unexpectedIds.length} document(s) diverge from stored WITHOUT an allowlist entry ` +
      `(${unexpected.length} field diffs).\n` +
      `Corpus divergent docs: ${divergentIds.length}; allowlisted: ${ALLOWLIST.length} ` +
      `(${Object.entries(allowlistByReason).map(([k, v]) => `${k}=${v}`).join(', ')}).\n` +
      `Unexpected (first 25): ${JSON.stringify(unexpected.slice(0, 25), null, 2)}\n` +
      `Each is EITHER a real kernel/service regression to fix, OR a new historical ` +
      `artifact to add (with a reason) to parity-replay-allowlist.json.`;
    expect(unexpected, message).toEqual([]);
  });
});
