import { describe, expect, it } from 'vitest';
import { writeFileSync } from 'node:fs';
import { cldrDayToDow, mapTerritoryFacts, territoryFactsToSql } from './cldrMapping';

const GENERATE = process.env.GENERATE === '1';

const currencyData = { supplemental: { currencyData: { region: {
  AE: [{ AED: { _from: '1973-05-19' } }],
  OM: [{ OMR: { _from: '1972-11-11' } }],
} } } };
const weekData = { supplemental: { weekData: {
  firstDay: { '001': 'mon', AE: 'sat', OM: 'sat' },
  weekendStart: { '001': 'sat', AE: 'sat', OM: 'fri' },
  weekendEnd: { '001': 'sun', AE: 'sun', OM: 'sat' },
} } };

describe('cldrMapping', () => {
  it('maps CLDR day names to registry dow numbers (0=Sun..6=Sat)', () => {
    expect(cldrDayToDow('mon')).toBe(1);
    expect(cldrDayToDow('fri')).toBe(5);
    expect(cldrDayToDow('sat')).toBe(6);
    expect(cldrDayToDow('sun')).toBe(0);
  });
  it('extracts the ACTIVE currency and weekend facts per territory', () => {
    const facts = mapTerritoryFacts(currencyData, weekData);
    expect(facts.get('OM')).toEqual({
      code: 'OM', currencyCode: 'OMR', weekendDays: [5, 6], weekStartsOn: 6,
    });
    expect(facts.get('AE')).toEqual({
      code: 'AE', currencyCode: 'AED', weekendDays: [6, 0], weekStartsOn: 6,
    });
  });
  it('emits fill-only-when-missing SQL (COALESCE + key-absence guards)', () => {
    const sql = territoryFactsToSql([...mapTerritoryFacts(currencyData, weekData).values()]);
    expect(sql).toContain("WHERE code = 'OM' AND deleted_at IS NULL");
    expect(sql).toContain('COALESCE(currency_code');
    expect(sql).toContain("country_config ? 'datetime.weekend_days'");
    expect(sql).not.toContain('DELETE');
    expect(sql).not.toContain('DROP');
  });
});

describe('CLDR seed generation (network — GENERATE=1 only)', () => {
  it.runIf(GENERATE)('fetches live CLDR and writes the operator seed', async () => {
    const fetchJson = async (url: string) => {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
      return res.json();
    };
    const [cur, week] = await Promise.all([
      fetchJson('https://unpkg.com/cldr-core@45.0.0/supplemental/currencyData.json'),
      fetchJson('https://unpkg.com/cldr-core@45.0.0/supplemental/weekData.json'),
    ]);
    const facts = mapTerritoryFacts(cur, week);
    expect(facts.size).toBeGreaterThan(150);
    const sql = `-- GENERATED by scripts/country-engine/import-cldr.test.ts (GENERATE=1).\n`
      + `-- Fill-only-when-missing locale facts from CLDR 45 (currencyData + weekData).\n`
      + `-- OPERATOR: review, then apply via mcp__supabase__apply_migration.\n\n`
      + territoryFactsToSql([...facts.values()]);
    writeFileSync('supabase/seeds/cldr_locale_facts.operator.sql', sql);
  });
});
